#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 4

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "QwnaB/Vq7704"
#define LAYER_STATE_8BIT

#define NAVIGATOR_TRACKBALL_CPI 30
#define NAVIGATOR_SCROLL_DIVIDER 50

#define AUTOMOUSE_LAYER 3
#define AUTOMOUSE_TIMEOUT 500
#define AUTOMOUSE_THRESHOLD 10
#define AUTOMOUSE_ONESHOT
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define RGB_MATRIX_STARTUP_SPD 60

